# Validators with SEV (AMD)
- mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
  start: 0
  count: 5
  balance: 32000000000
  wd_prefix: "0x01"
  wd_address: "0x1234567890abcdef1234567890abcdef12345678"
  tee_vendor: 0  # SEV for validators 0-4

# Validators with TDX (Intel)
- mnemonic: "legal winner thank year wave sausage worth useful legal winner thank yellow"
  start: 5
  count: 5
  balance: 32000000000
  wd_prefix: "0x02"
  wd_address: "0x2234567890abcdef1234567890abcdef12345678"
  tee_vendor: 1  # TDX for validators 5-9

# Validators with CCA (ARM)
- mnemonic: "letter advice cage absurd amount doctor acoustic avoid letter advice cage above"
  start: 10
  count: 5
  balance: 32000000000
  wd_prefix: "0x03"
  wd_address: "0x3234567890abcdef1234567890abcdef12345678"
  tee_vendor: 2  # CCA for validators 10-14
 